export enum VALID_RESOURCES {
  typeProcedures = 'types-procedures',
  communication = 'communication',
  institutions = 'institutions',
  dependencies = 'dependencies',
  groupware = 'groupware',
  external = 'external',
  internal = 'internal',
  officers = 'officers',
  archived = 'archived',
  accounts = 'accounts',
  reports = 'reports',
  roles = 'roles',
  jobs = 'jobs',
}
